"""AI Provider Boundary Schemas and DTO Contracts.

Defines vendor-independent, strictly-typed Pydantic v2 data models for the AI
provider abstraction layer, separating internal LLM provider boundaries from
HTTP API presentation DTOs.
"""

from typing import Any, Optional
import uuid

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)

from app.modules.viva.schemas import (
    EvaluationVerdictEnum,
    VivaDifficultyEnum,
    VivaProviderModeEnum,
    VivaTopicEnum,
)

# Re-export enums for provider boundary convenience
__all__ = [
    "VivaDifficultyEnum",
    "VivaTopicEnum",
    "EvaluationVerdictEnum",
    "VivaProviderModeEnum",
    "AIExperimentContext",
    "AIGeneratedQuestion",
    "QuestionGenerationRequest",
    "QuestionGenerationResponse",
    "AIEvaluationContextItem",
    "AnswerEvaluationRequest",
    "AnswerEvaluationResponse",
    "ParsedExperimentSections",
]


class ParsedExperimentSections(BaseModel):
    """Structured laboratory experiment sections extracted by AI parser."""

    title: Optional[str] = Field(
        default=None,
        max_length=255,
        description="Extracted or inferred experiment title",
    )
    subject: Optional[str] = Field(
        default=None,
        max_length=255,
        description="Academic subject area or laboratory course title",
    )
    experiment_number: Optional[str] = Field(
        default=None,
        max_length=50,
        serialization_alias="experimentNumber",
        description="Optional experiment catalog or sequence code (e.g. 'EXP-01')",
    )
    objective: Optional[str] = Field(
        default=None,
        description="Core experimental aim or objective",
    )
    theory: Optional[str] = Field(
        default=None,
        description="Theoretical background, governing principles, and scientific equations",
    )
    apparatus: Optional[str] = Field(
        default=None,
        description="Required laboratory apparatus, tools, components, and instruments",
    )
    procedure: Optional[str] = Field(
        default=None,
        description="Step-by-step experimental procedure and methodology",
    )
    observations: Optional[str] = Field(
        default=None,
        description="Expected observations, measurement tables, and reading parameters",
    )
    calculations: Optional[str] = Field(
        default=None,
        description="Formulas, calculations, derivations, and error analysis",
    )
    precautions: Optional[str] = Field(
        default=None,
        description="Laboratory safety precautions and handling guidelines",
    )
    result: Optional[str] = Field(
        default=None,
        description="Experimental result, inferences, or conclusion statement",
    )
    additional_notes: Optional[str] = Field(
        default=None,
        serialization_alias="additionalNotes",
        description="Additional relevant sections or notes present in the source text",
    )

    model_config = ConfigDict(extra="forbid", populate_by_name=True)



class AIExperimentContext(BaseModel):
    """Normalized experiment domain context supplied to AI providers for viva practice."""

    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1, max_length=255, description="Experiment title")
    subject: str = Field(min_length=1, max_length=255, description="Subject area")
    experiment_number: Optional[str] = Field(
        default=None, max_length=50, description="Experiment catalog number"
    )
    description: Optional[str] = Field(
        default=None, max_length=5000, description="Overview or syllabus abstract"
    )
    objective: Optional[str] = Field(
        default=None, max_length=5000, description="Stated experimental objective"
    )
    theory: Optional[str] = Field(
        default=None, max_length=15000, description="Underlying theoretical concepts and equations"
    )
    apparatus: Optional[str] = Field(
        default=None, max_length=5000, description="Required laboratory apparatus and tools"
    )
    procedure: Optional[str] = Field(
        default=None, max_length=15000, description="Step-by-step experimental procedure"
    )
    observations: Optional[str] = Field(
        default=None, max_length=10000, description="Expected observations and measurements"
    )
    calculations: Optional[str] = Field(
        default=None, max_length=10000, description="Formulas, calculations, and error analysis"
    )
    precautions: Optional[str] = Field(
        default=None, max_length=5000, description="Laboratory safety precautions"
    )


class AIGeneratedQuestion(BaseModel):
    """Single viva examination question generated by an AI provider."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique question identifier",
    )
    question_number: int = Field(
        ge=1,
        description="1-based sequence index within the session",
    )
    question_text: str = Field(
        min_length=5,
        max_length=2000,
        description="The oral examination question text",
    )
    topic: VivaTopicEnum = Field(description="Question topic category")
    difficulty: VivaDifficultyEnum = Field(
        default=VivaDifficultyEnum.INTERMEDIATE,
        description="Difficulty level of the question",
    )
    expected_answer: Optional[str] = Field(
        default=None,
        max_length=5000,
        description="Authoritative model answer for student review or rubric evaluation",
    )
    key_points: list[str] = Field(
        default_factory=list,
        description="Essential conceptual points required for a full score",
    )
    grounded_source_section: Optional[str] = Field(
        default=None,
        max_length=100,
        description="Lab manual source section (e.g. 'Theory', 'Apparatus', 'Procedure')",
    )


class QuestionGenerationRequest(BaseModel):
    """Payload to request viva examination questions from an AI provider."""

    model_config = ConfigDict(extra="forbid")

    experiment: AIExperimentContext = Field(
        description="Structured experiment manual context for question grounding"
    )
    question_count: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Target question count to generate (1 to 20)",
    )
    difficulty: VivaDifficultyEnum = Field(
        default=VivaDifficultyEnum.INTERMEDIATE,
        description="Requested difficulty level",
    )
    topic_focus: VivaTopicEnum = Field(
        default=VivaTopicEnum.MIXED,
        description="Topic focus area or 'mixed'",
    )
    constraints: list[str] = Field(
        default_factory=list,
        description="Optional provider constraints or instructional prompts",
    )


class QuestionGenerationResponse(BaseModel):
    """Collection of viva questions generated by an AI provider."""

    model_config = ConfigDict(extra="forbid")

    questions: list[AIGeneratedQuestion] = Field(
        min_length=1,
        description="Ordered collection of generated viva examination questions",
    )
    provider_mode: VivaProviderModeEnum = Field(
        description="Operational mode of the provider: 'demonstration' or 'ai-live'"
    )
    provider_id: str = Field(
        min_length=1,
        max_length=50,
        description="Identifier of the generating provider (e.g., 'gemini', 'demonstration')",
    )
    topic_distribution: dict[str, int] = Field(
        default_factory=dict,
        description="Summary question count by topic",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-independent operational metadata (e.g. latency, model name)",
    )

    @model_validator(mode="after")
    def populate_topic_distribution(self) -> "QuestionGenerationResponse":
        """Compute topic distribution map automatically if not explicitly provided."""
        if not self.topic_distribution and self.questions:
            dist: dict[str, int] = {}
            for q in self.questions:
                topic_val = q.topic.value if hasattr(q.topic, "value") else str(q.topic)
                dist[topic_val] = dist.get(topic_val, 0) + 1
            self.topic_distribution = dist
        return self


class AIEvaluationContextItem(BaseModel):
    """Contextual summary of a previously evaluated question within an ongoing viva session."""

    model_config = ConfigDict(extra="forbid")

    question_number: int = Field(ge=1, description="1-based question number")
    question_text: str = Field(min_length=1, max_length=2000, description="Question asked")
    student_answer: str = Field(min_length=1, max_length=5000, description="Submitted answer")
    verdict: EvaluationVerdictEnum = Field(description="Assigned verdict")
    score: int = Field(ge=0, le=10, description="Assigned score (0-10)")


class AnswerEvaluationRequest(BaseModel):
    """Payload to request evaluation of a student's answer from an AI provider."""

    model_config = ConfigDict(extra="forbid")

    question: AIGeneratedQuestion = Field(description="The question presented to the student")
    student_answer: str = Field(
        min_length=1,
        max_length=5000,
        description="Student's verbal or typed response",
    )
    experiment: Optional[AIExperimentContext] = Field(
        default=None,
        description="Optional experiment manual context for answer verification",
    )
    previous_answers: list[AIEvaluationContextItem] = Field(
        default_factory=list,
        description="Optional chronological session context of previous evaluations",
    )

    @field_validator("student_answer", mode="before")
    @classmethod
    def validate_student_answer_non_empty(cls, v: Any) -> str:
        """Ensure student answer is not null, empty, or whitespace-only."""
        if v is None:
            raise ValueError("Student answer cannot be null")
        if not isinstance(v, str):
            raise ValueError("Student answer must be a string")
        stripped = v.strip()
        if not stripped:
            raise ValueError("Student answer cannot be empty or whitespace-only")
        return stripped


class AnswerEvaluationResponse(BaseModel):
    """Standardized answer evaluation result produced by an AI provider."""

    model_config = ConfigDict(extra="forbid")

    verdict: EvaluationVerdictEnum = Field(
        description="Classification verdict: 'correct', 'partially-correct', 'incorrect'"
    )
    score: int = Field(
        ge=0,
        le=10,
        description="Rubric score on a standardized 0 to 10 scale",
    )
    feedback: str = Field(
        min_length=1,
        max_length=2000,
        description="Comprehensive summary evaluation feedback for the student",
    )
    what_you_got_right: str = Field(
        default="",
        max_length=3000,
        description="Concepts, laws, or formulas the student accurately explained",
    )
    what_was_missing: str = Field(
        default="",
        max_length=3000,
        description="Critical omissions, inaccuracies, or misconceptions in the response",
    )
    expected_answer: str = Field(
        default="",
        max_length=5000,
        description="Authoritative reference model answer for student learning",
    )
    improvement_tip: str = Field(
        default="",
        max_length=2000,
        description="Actionable advice for subsequent viva voce examinations",
    )
    key_points_covered: list[str] = Field(
        default_factory=list,
        description="Rubric key points satisfactorily satisfied by the student",
    )
    key_points_missed: list[str] = Field(
        default_factory=list,
        description="Rubric key points omitted or misunderstood by the student",
    )
    provider_mode: VivaProviderModeEnum = Field(
        description="Provider operational mode: 'demonstration' or 'ai-live'"
    )
    provider_id: str = Field(
        min_length=1,
        max_length=50,
        description="Identifier of evaluating provider (e.g., 'gemini', 'demonstration')",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-independent operational metadata (e.g. latency, token usage)",
    )
